[MtBar1]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc1
X=(0 * #BarTotalWidth#)
[MtBar2]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc2
X=(1 * #BarTotalWidth#)
[MtBar3]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc3
X=(2 * #BarTotalWidth#)
[MtBar4]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc4
X=(3 * #BarTotalWidth#)
[MtBar5]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc5
X=(4 * #BarTotalWidth#)
[MtBar6]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc6
X=(5 * #BarTotalWidth#)
[MtBar7]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc7
X=(6 * #BarTotalWidth#)
[MtBar8]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc8
X=(7 * #BarTotalWidth#)
[MtBar9]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc9
X=(8 * #BarTotalWidth#)
[MtBar10]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc10
X=(9 * #BarTotalWidth#)
[MtBar11]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc11
X=(10 * #BarTotalWidth#)
[MtBar12]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc12
X=(11 * #BarTotalWidth#)
[MtBar13]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc13
X=(12 * #BarTotalWidth#)
[MtBar14]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc14
X=(13 * #BarTotalWidth#)
[MtBar15]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc15
X=(14 * #BarTotalWidth#)
[MtBar16]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc16
X=(15 * #BarTotalWidth#)
[MtBar17]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc17
X=(16 * #BarTotalWidth#)
[MtBar18]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc18
X=(17 * #BarTotalWidth#)
[MtBar19]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc19
X=(18 * #BarTotalWidth#)
[MtBar20]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc20
X=(19 * #BarTotalWidth#)
[MtBar21]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc21
X=(20 * #BarTotalWidth#)
[MtBar22]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc22
X=(21 * #BarTotalWidth#)
[MtBar23]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc23
X=(22 * #BarTotalWidth#)
[MtBar24]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc24
X=(23 * #BarTotalWidth#)
[MtBar25]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc25
X=(24 * #BarTotalWidth#)
[MtBar26]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc26
X=(25 * #BarTotalWidth#)
[MtBar27]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc27
X=(26 * #BarTotalWidth#)
[MtBar28]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc28
X=(27 * #BarTotalWidth#)
[MtBar29]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc29
X=(28 * #BarTotalWidth#)
[MtBar30]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc30
X=(29 * #BarTotalWidth#)
[MtBar31]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc31
X=(30 * #BarTotalWidth#)
[MtBar32]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc32
X=(31 * #BarTotalWidth#)
[MtBar33]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc33
X=(32 * #BarTotalWidth#)
[MtBar34]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc34
X=(33 * #BarTotalWidth#)
[MtBar35]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc35
X=(34 * #BarTotalWidth#)
[MtBar36]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc36
X=(35 * #BarTotalWidth#)
[MtBar37]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc37
X=(36 * #BarTotalWidth#)
[MtBar38]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc38
X=(37 * #BarTotalWidth#)
[MtBar39]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc39
X=(38 * #BarTotalWidth#)
[MtBar40]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc40
X=(39 * #BarTotalWidth#)
[MtBar41]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc41
X=(40 * #BarTotalWidth#)
[MtBar42]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc42
X=(41 * #BarTotalWidth#)
[MtBar43]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc43
X=(42 * #BarTotalWidth#)
[MtBar44]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc44
X=(43 * #BarTotalWidth#)
[MtBar45]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc45
X=(44 * #BarTotalWidth#)
[MtBar46]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc46
X=(45 * #BarTotalWidth#)
[MtBar47]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc47
X=(46 * #BarTotalWidth#)
[MtBar48]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc48
X=(47 * #BarTotalWidth#)
[MtBar49]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc49
X=(48 * #BarTotalWidth#)
[MtBar50]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc50
X=(49 * #BarTotalWidth#)
[MtBar51]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc51
X=(50 * #BarTotalWidth#)
[MtBar52]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc52
X=(51 * #BarTotalWidth#)
[MtBar53]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc53
X=(52 * #BarTotalWidth#)
[MtBar54]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc54
X=(53 * #BarTotalWidth#)
[MtBar55]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc55
X=(54 * #BarTotalWidth#)
[MtBar56]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc56
X=(55 * #BarTotalWidth#)
[MtBar57]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc57
X=(56 * #BarTotalWidth#)
[MtBar58]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc58
X=(57 * #BarTotalWidth#)
[MtBar59]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc59
X=(58 * #BarTotalWidth#)
[MtBar60]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc60
X=(59 * #BarTotalWidth#)
[MtBar61]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc61
X=(60 * #BarTotalWidth#)
[MtBar62]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc62
X=(61 * #BarTotalWidth#)
[MtBar63]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc63
X=(62 * #BarTotalWidth#)
[MtBar64]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc64
X=(63 * #BarTotalWidth#)
[MtBar65]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc65
X=(64 * #BarTotalWidth#)
[MtBar66]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc66
X=(65 * #BarTotalWidth#)
[MtBar67]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc67
X=(66 * #BarTotalWidth#)
[MtBar68]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc68
X=(67 * #BarTotalWidth#)
[MtBar69]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc69
X=(68 * #BarTotalWidth#)
[MtBar70]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc70
X=(69 * #BarTotalWidth#)
[MtBar71]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc71
X=(70 * #BarTotalWidth#)
[MtBar72]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc72
X=(71 * #BarTotalWidth#)
[MtBar73]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc73
X=(72 * #BarTotalWidth#)
[MtBar74]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc74
X=(73 * #BarTotalWidth#)
[MtBar75]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc75
X=(74 * #BarTotalWidth#)
[MtBar76]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc76
X=(75 * #BarTotalWidth#)
[MtBar77]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc77
X=(76 * #BarTotalWidth#)
[MtBar78]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc78
X=(77 * #BarTotalWidth#)
[MtBar79]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc79
X=(78 * #BarTotalWidth#)
[MtBar80]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc80
X=(79 * #BarTotalWidth#)
[MtBar81]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc81
X=(80 * #BarTotalWidth#)
[MtBar82]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc82
X=(81 * #BarTotalWidth#)
[MtBar83]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc83
X=(82 * #BarTotalWidth#)
[MtBar84]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc84
X=(83 * #BarTotalWidth#)
[MtBar85]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc85
X=(84 * #BarTotalWidth#)
[MtBar86]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc86
X=(85 * #BarTotalWidth#)
[MtBar87]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc87
X=(86 * #BarTotalWidth#)
[MtBar88]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc88
X=(87 * #BarTotalWidth#)
[MtBar89]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc89
X=(88 * #BarTotalWidth#)
[MtBar90]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc90
X=(89 * #BarTotalWidth#)
[MtBar91]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc91
X=(90 * #BarTotalWidth#)
[MtBar92]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc92
X=(91 * #BarTotalWidth#)
[MtBar93]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc93
X=(92 * #BarTotalWidth#)
[MtBar94]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc94
X=(93 * #BarTotalWidth#)
[MtBar95]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc95
X=(94 * #BarTotalWidth#)
[MtBar96]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc96
X=(95 * #BarTotalWidth#)
[MtBar97]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc97
X=(96 * #BarTotalWidth#)
[MtBar98]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc98
X=(97 * #BarTotalWidth#)
[MtBar99]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc99
X=(98 * #BarTotalWidth#)
[MtBar100]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc100
X=(99 * #BarTotalWidth#)
[MtBar101]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc101
X=(100 * #BarTotalWidth#)
[MtBar102]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc102
X=(101 * #BarTotalWidth#)
[MtBar103]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc103
X=(102 * #BarTotalWidth#)
[MtBar104]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc104
X=(103 * #BarTotalWidth#)
[MtBar105]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc105
X=(104 * #BarTotalWidth#)
[MtBar106]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc106
X=(105 * #BarTotalWidth#)
[MtBar107]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc107
X=(106 * #BarTotalWidth#)
[MtBar108]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc108
X=(107 * #BarTotalWidth#)
[MtBar109]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc109
X=(108 * #BarTotalWidth#)
[MtBar110]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc110
X=(109 * #BarTotalWidth#)
[MtBar111]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc111
X=(110 * #BarTotalWidth#)
[MtBar112]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc112
X=(111 * #BarTotalWidth#)
[MtBar113]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc113
X=(112 * #BarTotalWidth#)
[MtBar114]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc114
X=(113 * #BarTotalWidth#)
[MtBar115]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc115
X=(114 * #BarTotalWidth#)
[MtBar116]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc116
X=(115 * #BarTotalWidth#)
[MtBar117]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc117
X=(116 * #BarTotalWidth#)
[MtBar118]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc118
X=(117 * #BarTotalWidth#)
[MtBar119]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc119
X=(118 * #BarTotalWidth#)
[MtBar120]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc120
X=(119 * #BarTotalWidth#)
[MtBar121]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc121
X=(120 * #BarTotalWidth#)
[MtBar122]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc122
X=(121 * #BarTotalWidth#)
[MtBar123]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc123
X=(122 * #BarTotalWidth#)
[MtBar124]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc124
X=(123 * #BarTotalWidth#)
[MtBar125]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc125
X=(124 * #BarTotalWidth#)
[MtBar126]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc126
X=(125 * #BarTotalWidth#)
[MtBar127]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc127
X=(126 * #BarTotalWidth#)
[MtBar128]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc128
X=(127 * #BarTotalWidth#)
[MtBar129]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc129
X=(128 * #BarTotalWidth#)
[MtBar130]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc130
X=(129 * #BarTotalWidth#)
[MtBar131]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc131
X=(130 * #BarTotalWidth#)
[MtBar132]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc132
X=(131 * #BarTotalWidth#)
[MtBar133]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc133
X=(132 * #BarTotalWidth#)
[MtBar134]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc134
X=(133 * #BarTotalWidth#)
[MtBar135]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc135
X=(134 * #BarTotalWidth#)
[MtBar136]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc136
X=(135 * #BarTotalWidth#)
[MtBar137]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc137
X=(136 * #BarTotalWidth#)
[MtBar138]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc138
X=(137 * #BarTotalWidth#)
[MtBar139]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc139
X=(138 * #BarTotalWidth#)
[MtBar140]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc140
X=(139 * #BarTotalWidth#)
[MtBar141]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc141
X=(140 * #BarTotalWidth#)
[MtBar142]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc142
X=(141 * #BarTotalWidth#)
[MtBar143]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc143
X=(142 * #BarTotalWidth#)
[MtBar144]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc144
X=(143 * #BarTotalWidth#)
[MtBar145]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc145
X=(144 * #BarTotalWidth#)
[MtBar146]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc146
X=(145 * #BarTotalWidth#)
[MtBar147]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc147
X=(146 * #BarTotalWidth#)
[MtBar148]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc148
X=(147 * #BarTotalWidth#)
[MtBar149]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc149
X=(148 * #BarTotalWidth#)
[MtBar150]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc150
X=(149 * #BarTotalWidth#)
[MtBar151]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc151
X=(150 * #BarTotalWidth#)
[MtBar152]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc152
X=(151 * #BarTotalWidth#)
[MtBar153]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc153
X=(152 * #BarTotalWidth#)
[MtBar154]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc154
X=(153 * #BarTotalWidth#)
[MtBar155]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc155
X=(154 * #BarTotalWidth#)
[MtBar156]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc156
X=(155 * #BarTotalWidth#)
[MtBar157]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc157
X=(156 * #BarTotalWidth#)
[MtBar158]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc158
X=(157 * #BarTotalWidth#)
[MtBar159]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc159
X=(158 * #BarTotalWidth#)
[MtBar160]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc160
X=(159 * #BarTotalWidth#)
[MtBar161]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc161
X=(160 * #BarTotalWidth#)
[MtBar162]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc162
X=(161 * #BarTotalWidth#)
[MtBar163]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc163
X=(162 * #BarTotalWidth#)
[MtBar164]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc164
X=(163 * #BarTotalWidth#)
[MtBar165]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc165
X=(164 * #BarTotalWidth#)
[MtBar166]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc166
X=(165 * #BarTotalWidth#)
[MtBar167]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc167
X=(166 * #BarTotalWidth#)
[MtBar168]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc168
X=(167 * #BarTotalWidth#)
[MtBar169]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc169
X=(168 * #BarTotalWidth#)
[MtBar170]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc170
X=(169 * #BarTotalWidth#)
[MtBar171]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc171
X=(170 * #BarTotalWidth#)
[MtBar172]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc172
X=(171 * #BarTotalWidth#)
[MtBar173]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc173
X=(172 * #BarTotalWidth#)
[MtBar174]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc174
X=(173 * #BarTotalWidth#)
[MtBar175]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc175
X=(174 * #BarTotalWidth#)
[MtBar176]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc176
X=(175 * #BarTotalWidth#)
[MtBar177]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc177
X=(176 * #BarTotalWidth#)
[MtBar178]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc178
X=(177 * #BarTotalWidth#)
[MtBar179]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc179
X=(178 * #BarTotalWidth#)
[MtBar180]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc180
X=(179 * #BarTotalWidth#)
[MtBar181]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc181
X=(180 * #BarTotalWidth#)
[MtBar182]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc182
X=(181 * #BarTotalWidth#)
[MtBar183]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc183
X=(182 * #BarTotalWidth#)
[MtBar184]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc184
X=(183 * #BarTotalWidth#)
[MtBar185]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc185
X=(184 * #BarTotalWidth#)
[MtBar186]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc186
X=(185 * #BarTotalWidth#)
[MtBar187]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc187
X=(186 * #BarTotalWidth#)
[MtBar188]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc188
X=(187 * #BarTotalWidth#)
[MtBar189]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc189
X=(188 * #BarTotalWidth#)
[MtBar190]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc190
X=(189 * #BarTotalWidth#)
[MtBar191]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc191
X=(190 * #BarTotalWidth#)
[MtBar192]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc192
X=(191 * #BarTotalWidth#)
[MtBar193]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc193
X=(192 * #BarTotalWidth#)
[MtBar194]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc194
X=(193 * #BarTotalWidth#)
[MtBar195]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc195
X=(194 * #BarTotalWidth#)
[MtBar196]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc196
X=(195 * #BarTotalWidth#)
[MtBar197]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc197
X=(196 * #BarTotalWidth#)
[MtBar198]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc198
X=(197 * #BarTotalWidth#)
[MtBar199]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc199
X=(198 * #BarTotalWidth#)
[MtBar200]
Meter=Bar
MeterStyle=StBar
MeasureName=MsCalc200
X=(199 * #BarTotalWidth#)